/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cg;

public class MoodAnalyser {
	public static String message;

	public MoodAnalyser() {

	}

	public MoodAnalyser(String message) {
		this.message = message;
	}
	
	public String analyseMood(String message) throws MoodAnalyserException{
		this.message = message;
		return analyseMood();
	}
	
	public String analyseMood() throws MoodAnalyserException{
		try {
		if(message.length() == 0)
			throw new MoodAnalyserException(MoodAnalyserException.ExceptionType.ENTERED_EMPTY, "Please Enter Some Message");
		
			if (message.contains("Happy"))
				return "SAD";
			else
				return "HAPPY";
		}catch(NullPointerException e) {
			throw new MoodAnalyserException(MoodAnalyserException.ExceptionType.ENTERED_NULL, "Can't be NULL");
		}
	}
}