/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cg;

public class MoodAnalyser {
	public String message;
	
	public MoodAnalyser() {
	}
	
	public MoodAnalyser(String message) {
		this.message = message;
	}
	
	public String analyseMood() {
		try {
			if (message.contains("Happy"))
				return "HAPPY";
			else
				return "SAD";
		}catch(NullPointerException e) {
			return "NULL";
		}
	}
}