/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cg;

import org.junit.*;

import com.cg.MoodAnalyser;

public class MoodAnalyserTest {
	//TC1.1
	@Test
	public void givenMessage_whenSad_ShouldReturnSad() {
		MoodAnalyser moodAnalyser = new MoodAnalyser();
		String mood = moodAnalyser.analyseMood("I am in Sad mood");
		Assert.assertEquals("SAD", mood);
	}
	//TC1.2
	@Test
	public void givenMessage_whenNotSad_ShouldReturnHappy() {
		MoodAnalyser moodAnalyser = new MoodAnalyser();
		String mood = moodAnalyser.analyseMood("I am in Any Mood");
		Assert.assertEquals("HAPPY", mood);
	}
}