/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cg;

import org.junit.*;

import com.cg.MoodAnalyser;

public class MoodAnalyserTest {
	@Test
	public void TestMood() {
		MoodAnalyser moodAnalyser = new MoodAnalyser(null);
		String mood = moodAnalyser.analyseMood();
		Assert.assertEquals("HAPPY", mood);
	}
}